const express=require('express');const path=require('path');const session=require('express-session');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');
const app=express();const db=new Database(path.join(__dirname,'data','omh.db'));db.pragma('journal_mode=WAL');
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
app.use(express.static(path.join(__dirname,'public')));
db.exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,category TEXT,name TEXT,description TEXT,unit TEXT,price TEXT,icon TEXT,image TEXT,active INTEGER DEFAULT 1,sort INTEGER DEFAULT 0);CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,rating INTEGER,comment TEXT,approved INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,service TEXT,quantity TEXT,contact TEXT,message TEXT,status TEXT DEFAULT 'new',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const defaults={brand:'OMH Social Services',tagline:'مرجع خدمات نوین دیجیتال',description:'بهترین و سریع‌ترین خدمات دیجیتال با تمرکز بر کیفیت، اعتبار و امنیت.',whatsapp:'93748070273',whatsappChannel:'https://whatsapp.com/channel/0029VbC27wl9mrGcV1D6aa3O',whatsappGroup:'https://chat.whatsapp.com/LhwXxaXGEy5F4pq0GdqV5s?s=cl&p=a&ilr=0',telegramChannel:'https://t.me/OMHSocialServices',telegram:'@omhsocial',email:'omhsocialservices@gmail.com',heroTitle:'حضور دیجیتال خود را به سطح بالاتری ببرید',heroText:'خدمات شبکه‌های اجتماعی، شماره‌های مجازی و طراحی دیجیتال در یک مرجع.',aboutTitle:'چرا OMH؟',aboutText:'کیفیت، اعتبار، سرعت و رضایت مشتری اولویت اصلی ماست.',payment:'کریدیت و مومو'};
for(const [k,v] of Object.entries(defaults))db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v);
const cats=['Facebook Service','Instagram Service','WhatsApp Service','Telegram Service','TikTok Service','Digital & Design Services','Virtual Numbers','Accounts'];for(const c of cats)db.prepare('INSERT OR IGNORE INTO services(id,category,name,description,unit,price,icon,active,sort) VALUES(NULL,?,?,?,?,?,?,?,?,?)').run(c,'', '', '', '', '','1',0);
function settings(){return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))}function auth(req,res,next){if(!req.session.admin)return res.status(401).json({error:'Unauthorized'});next()}
app.get('/api/public',(_,res)=>res.json({settings:settings(),services:db.prepare('SELECT * FROM services WHERE active=1 ORDER BY category,sort,id').all(),reviews:db.prepare('SELECT * FROM reviews WHERE approved=1 ORDER BY id DESC').all()}));
app.post('/api/reviews',(req,res)=>{const {name,rating,comment}=req.body;if(!name||!comment)return res.status(400).json({error:'نام و نظر الزامی است'});db.prepare('INSERT INTO reviews(name,rating,comment) VALUES(?,?,?)').run(name,Math.min(5,Math.max(1,Number(rating)||5)),comment);res.json({ok:true,message:'نظر شما پس از بررسی منتشر می‌شود.'})});
app.post('/api/orders',(req,res)=>{const {name,service,quantity,contact,message}=req.body;if(!name||!contact)return res.status(400).json({error:'نام و راه ارتباطی الزامی است'});const r=db.prepare('INSERT INTO orders(name,service,quantity,contact,message) VALUES(?,?,?,?,?)').run(name,service||'',quantity||'',contact,message||'');res.json({ok:true,id:r.lastInsertRowid})});
app.post('/api/login',(req,res)=>{const p=process.env.ADMIN_PASSWORD;if(!p)return res.status(500).json({error:'ADMIN_PASSWORD تنظیم نشده است'});if(req.body.password===p){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:'رمز نادرست است'})});app.post('/api/logout',auth,(req,res)=>{req.session.destroy(()=>res.json({ok:true}))});app.get('/api/admin',auth,(_,res)=>res.json({settings:settings(),services:db.prepare('SELECT * FROM services ORDER BY category,sort,id').all(),reviews:db.prepare('SELECT * FROM reviews ORDER BY id DESC').all(),orders:db.prepare('SELECT * FROM orders ORDER BY id DESC').all()}));
app.put('/api/settings',auth,(req,res)=>{const q=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');const tx=db.transaction(o=>{for(const [k,v] of Object.entries(o))q.run(k,String(v??''))});tx(req.body);res.json({ok:true})});
app.post('/api/services',auth,(req,res)=>{const {category,name='',description='',unit='',price='',icon='',image='',active=1,sort=0}=req.body;const r=db.prepare('INSERT INTO services(category,name,description,unit,price,icon,image,active,sort) VALUES(?,?,?,?,?,?,?,?,?)').run(category,name,description,unit,price,icon,image,active?1:0,sort);res.json({id:r.lastInsertRowid})});app.put('/api/services/:id',auth,(req,res)=>{const f=['category','name','description','unit','price','icon','image','active','sort'];const a=f.map(k=>req.body[k]??'');db.prepare(`UPDATE services SET ${f.map(k=>k+'=?').join(',')} WHERE id=?`).run(...a,req.params.id);res.json({ok:true})});app.delete('/api/services/:id',auth,(req,res)=>{db.prepare('DELETE FROM services WHERE id=?').run(req.params.id);res.json({ok:true})});
app.put('/api/reviews/:id',auth,(req,res)=>{db.prepare('UPDATE reviews SET approved=? WHERE id=?').run(req.body.approved?1:0,req.params.id);res.json({ok:true})});app.delete('/api/reviews/:id',auth,(req,res)=>{db.prepare('DELETE FROM reviews WHERE id=?').run(req.params.id);res.json({ok:true})});app.put('/api/orders/:id',auth,(req,res)=>{db.prepare('UPDATE orders SET status=? WHERE id=?').run(req.body.status||'new',req.params.id);res.json({ok:true})});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('OMH running'));
